### PR TITLE
Improve README and fix one small hard-coded LLM name

### PR DESCRIPTION
**Pull request by shinglyu**

### CODE REVIEW

**Comment by calvincchan** [comment]
@shinglyu thanks for your contribution! I am sorry for the long delay since I was not aware of the PR. By the way did you check out GPT4All? It also support RAG with Logseq journal.

**Comment by shinglyu** [comment]
I am now using AnythingLLM, and I'm waiting for its auto-sync local files feature to come out of Beta. Works great so far

**Comment by calvincchan** [comment]
Thanks for sharing, I didn't know about AnythingLLM so I'll check it out.

One thing I'm curious through is that what embedding model do AnythingLLM or GPT3All use. Looks like there is no config for that. It seems that choosing the right embedding model can also contribute to better response.

**Comment by calvincchan** [comment]
Upon closer look, AnythingLLM does allow you to choose embedding model. Neat.

**Pull request merged**
